spring:
  application:
    name: spring-security-oauth2-jwt
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:my-database}
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:root}
jwt:
  publicKey: classpath:public.key
  privateKey: classpath:private.key
  expires: 3000
  issuer: my-service-auth